
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 43;
  public static final int OPEN_PAREN = 44;
  public static final int NEW_ARRAY = 9;
  public static final int STR = 8;
  public static final int READINT = 28;
  public static final int DOUBLE = 7;
  public static final int INT = 6;
  public static final int MINUS = 41;
  public static final int FOR = 25;
  public static final int SEMICOLON = 37;
  public static final int NOT = 4;
  public static final int AND = 2;
  public static final int LT = 31;
  public static final int IMPLEM = 15;
  public static final int INTERF = 17;
  public static final int CLOSE_PAREN = 45;
  public static final int DOUBLENUM = 51;
  public static final int OR = 3;
  public static final int COMMA = 39;
  public static final int BOOL = 5;
  public static final int CLASS = 16;
  public static final int NUM = 50;
  public static final int PLUS = 40;
  public static final int ASSIGN = 29;
  public static final int IF = 19;
  public static final int THIS = 14;
  public static final int DOT = 38;
  public static final int EOF = 0;
  public static final int RETURN = 21;
  public static final int TRUE = 10;
  public static final int NEW = 23;
  public static final int error = 1;
  public static final int OPEN_BRACE = 48;
  public static final int NULL = 13;
  public static final int MOD = 36;
  public static final int CLOSE_BRACKET = 47;
  public static final int OPEN_BRACKET = 46;
  public static final int BREAK = 22;
  public static final int VOID = 12;
  public static final int READLN = 27;
  public static final int EQ = 30;
  public static final int TIMES = 42;
  public static final int DOUBLE_SCI = 52;
  public static final int ELSE = 20;
  public static final int NOT_EQ = 35;
  public static final int WHILE = 24;
  public static final int LESS_EQ = 32;
  public static final int EXTENDS = 18;
  public static final int STRING = 54;
  public static final int CLOSE_BRACE = 49;
  public static final int FALSE = 11;
  public static final int GT = 33;
  public static final int PRINT = 26;
  public static final int IDENTIFIER = 53;
  public static final int GREATER_EQ = 34;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "AND",
  "OR",
  "NOT",
  "BOOL",
  "INT",
  "DOUBLE",
  "STR",
  "NEW_ARRAY",
  "TRUE",
  "FALSE",
  "VOID",
  "NULL",
  "THIS",
  "IMPLEM",
  "CLASS",
  "INTERF",
  "EXTENDS",
  "IF",
  "ELSE",
  "RETURN",
  "BREAK",
  "NEW",
  "WHILE",
  "FOR",
  "PRINT",
  "READLN",
  "READINT",
  "ASSIGN",
  "EQ",
  "LT",
  "LESS_EQ",
  "GT",
  "GREATER_EQ",
  "NOT_EQ",
  "MOD",
  "SEMICOLON",
  "DOT",
  "COMMA",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "OPEN_PAREN",
  "CLOSE_PAREN",
  "OPEN_BRACKET",
  "CLOSE_BRACKET",
  "OPEN_BRACE",
  "CLOSE_BRACE",
  "NUM",
  "DOUBLENUM",
  "DOUBLE_SCI",
  "IDENTIFIER",
  "STRING"
  };
}

